### ISSUE TITLE
Using SideMenu with a TabBarController?

### ISSUE THREAD

**Issue by jackdem** [handsomecode/InteractiveSideMenu#52]
I currently use sidemenu and it instantiates its controller tabs when it inits. 

Issue is i want to use a tab bar controller inside my first view controller tab, which can quick link me to 3-4 other controllers that are also in the sidemenu.

What approach is needed architecturally to allow for the tab bar controller to instantiate its controllers without overlapping with those created by the sidemenu?

Thanks

**Comment by okonor** [comment]
Hi @jackdem, 

I've updated a Sample to implement desired behavior: https://cl.ly/2y1y2B0S2P2o.
You can find a zip [here](https://cl.ly/2S2u1A38072j).

Save `tabBarViewContoller` as a property of `HostViewController`:
```swift
self.tabBarViewController = self.storyboard?.instantiateViewController(withIdentifier: "TabBar") as? UITabBarController 
self.selectContentViewController(tabBarViewController!)
```

Add `selectTab` func implementation:
```swift
func selectTab(_ index: Int) { 
    tabBarViewController?.selectedIndex = index 
}
```

On `tableView`'s item click in `NavigationMenuViewController` you should call this method instead of selecting ViewController as new SideMenu item. 
```swift
if let hostViewController = menuContainerViewController as? HostViewController { 
    hostViewController.selectTab(indexPath.row) 
}
menuContainerViewController.hideSideMenu()
```
Also, when tab is clicked from TabBar screen, side menu should highlight corresponding item. I didn't handle this in the Sample.

Hope, it'll be helpful.
Please, have fun using InteractiveSideMenuLibrary!

**Comment by jackdem** [comment]
thanks for this, why is it focused around a tab bar? i have the issue on my views that are simply in navigation controllers selected from the side menu, no use of tab bar

**Comment by jackdem** [comment]
thanks, this only works if there are the same items in the tab bar as in the side menu? i have 4 items in the tab bar but 15 in the side menu. I can only change to the first 4?

**Comment by okonor** [comment]
You can add as many items as you want in the menu, including tabBar's ones. But in this case you should work with the menu as usual and use `selectContentViewController` for switching items, when you are sure that user switches from tab bar ViewController to another and otherwise. You could use a flag responsible for information about current state.

In the case when user switches from one tab to another you can use `selectTab` method to prevent extra controllers presenting.

I don't see any limitations to use library for your case. If you face some issues, please, ask them.
