### ISSUE TITLE
when select side menu item than canter view issue

### ISSUE THREAD

**Issue by test-ineed** [handsomecode/InteractiveSideMenu#72]
![simulator screen shot - iphone 6 - 2018-01-31 at 12 50 13](https://user-images.githubusercontent.com/5210868/35679670-f797b7c2-077d-11e8-953e-6df3eb1ed072.png)
![simulator screen shot - iphone 6 - 2018-01-31 at 12 50 19](https://user-images.githubusercontent.com/5210868/35679671-f7e5f126-077d-11e8-8827-ab703bfba244.png)
![simulator screen shot - iphone 6 - 2018-01-31 at 12 50 24](https://user-images.githubusercontent.com/5210868/35679672-f8253a84-077d-11e8-9824-05476e5901af.png)

**Comment by test-ineed** [comment]
it's only happen in iOS 11 and above

**Comment by test-ineed** [comment]
using safe area.

**Comment by enmiller** [comment]
@test-ineed 
There appears to be a critical range with the contentScale property of the TransitionOptions that causes the odd behavior. When using a contentScale of 0.87 - 0.90, there seems to be an issue with the content controller's view not getting its safeAreaInsets set properly. From testing, I can only see it affecting those four values in that range.

I will continue to look into the issue but, for now, I will update the default value of the contentScale to be outside of this range so that the library works on iOS 11 by default

For now, you can change the `transitionOptions` to be outside of that range and you should see things improve.

**Comment by enmiller** [comment]
@test-ineed 
Try using `2.2.1`.  The default `contentScale` was changed to be outside of the affected range that causes the `safeAreaInsets` not to be set properly on the content controller.  

I will still be looking into this issue to see how I can make things work no matter the `contentScale` setting but this is the best I can do for now.
